server:
  port: 8007

spring:
  aop:
    auto: true
　　datasource:
  　　type: com.alibaba.druid.pool.DruidDataSource
  　　driver-class-name: org.gjt.mm.mysql.Driver
  　　url: jdbc:mysql://localhost:3306/corey_wechat
  　　username: root
  　　password: 123456
  　　filters: stat,wall,log4j     #druid监控配置


#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis :
  mapperLocations : classpath*:mapper/*.xml
  executor-type : reuse
  type-aliases-package : com.*
  configuration :
    map-underscore-to-camel-case : true
