server:
  port: 8007

spring:
  aop:
    auto: true
　　datasource:
  　　type: com.alibaba.druid.pool.DruidDataSource
  　　driver-class-name: org.gjt.mm.mysql.Driver
  　　url: jdbc:mysql://localhost:3306/corey_wechat?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  　　username: root
  　　password: 123456
  　　filters: stat,wall,log4j     #druid监控配置
  　　dbcp2:
    　　min-idle: 5         #数据库连接池的最小维持连接数
    　　initial-size: 5     #初始化提供的连接数
    　　max-total: 5          #最大的连接数
    　　max-wait-millis: 200        #等待连接获取的最大超时时间


#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis :
  mapperLocations : classpath*:mapper/*.xml
  executor-type : reuse
  type-aliases-package : com.*
  configuration :
    map-underscore-to-camel-case : true