server:
  port: 6014

spring:          #表示该配置直接为Spring容器负责处理
　　datasource:
  　　type: com.alibaba.druid.pool.DruidDataSource   #配置当前要使用的数据源的操作类型那个
  　　driver-class-name: org.gjt.mm.mysql.Driver       #配置MySQL的驱动程序类
  　　url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
  　　username: root
  　　password: 123456
  　　filters: stat,wall,log4j     #druid监控配置
  　　dbcp2:
    　　min-idle: 5         #数据库连接池的最小维持连接数
    　　initial-size: 5     #初始化提供的连接数
    　　max-total: 5          #最大的连接数
    　　max-wait-millis: 200        #等待连接获取的最大超时时间